### PR TITLE
Make winit backend exit on Super-Q

### PR DESCRIPTION
**Pull request by wezm**

### CODE REVIEW

**Comment by vberger** [comment]
Could you explain this change?

I fail to see how the dispatching of clients returning an error is linked to making anvil exit on Super+Q to be honest.

**Comment by wezm** [comment]
I modified the loop to mirror the udev backend as the winit one did not handle `running` being set to `false`. It seemed sensible to make them consistent.

**Comment by vberger** [comment]
Oh, right I see, thanks!

**Comment by wezm** [comment]
Sorry about the formatting. Should be fixed now.

**Comment by vberger** [comment]
Sorry for leaving this alone for such a long time, this is all good. :sweat_smile:

**Comment by wezm** [comment]
No worries, thanks for merging :+1:

**Pull request merged**
