### PR TITLE
Make `smithay::desktop::Window` support XWayland windows

### PR DESCRIPTION
**Pull request by saihaze**
As mentioned in https://github.com/Smithay/smithay/issues/1202, `Window` is supposed to abstract over both Xdg toplevels and X11 surfaces. So now I have done it.
There is a breaking API change - `Window::toplevel()` now returns an `Option`. And the `new()` function will be deprecated, replaced by `new_wayland_window()` and `new_x11_window()`.
Fixes are applied to Smallvil and Anvil to make them compile and work. But to take full advantage of this PR, Anvil may need major refactor in the future.

### CODE REVIEW

**Comment by colinmarc** [comment]
In my compositor, I have a similar abstraction, but I delay the creation of the wrapping object for an X11 window (and the mapping of the window) until the surface has been matched (until `wl_surface()` returns `Some`). 

I'm not sure how robust that is, but it seems to work, and I suspect there are significant benefits to holding the invariant that a mapped window always has a surface. I see that this just adds `unwrap` everywhere in Anvil for now, but my experience was that it's actually quite hard to do much with a window that doesn't have a surface anyway, so you end up pushing that "delay until the surface is matched" code into a bunch of places on the compositor side.

**Comment by saihaze** [comment]
> 

> In my compositor, I have a similar abstraction, but I delay the creation of the wrapping object for an X11 window (and the mapping of the window) until the surface has been matched (until `wl_surface()` returns `Some`).
> 
> I'm not sure how robust that is (and tbc, I'm new to all this), but it seems to work, and I suspect there are significant benefits to holding the invariant that a mapped window always has a surface. I see that this just adds `unwrap` everywhere in Anvil for now, but my experience was that it's actually quite hard to do much with a window that doesn't have a surface anyway, so you end up pushing that "delay until the surface is matched" code into a bunch of places on the compositor side.

The original design of `toplevel()` assumes that the window must be a Wayland one. But an X11 window will never have a `ToplevelSurface`. That's why an `Option` is returned instead now.

**Comment by colinmarc** [comment]
> The original design of `toplevel()` assumes that the window must be a Wayland one. But an X11 window will never have a `ToplevelSurface`. That's why an `Option` is returned instead now.

Right - to clarify, I'm talking about the `wl_surface` part, and the fact that X11Windows may or may not have a `wl_surface` yet when they get mapped, because of a race. I was suggesting a way to get around the following problematic pattern:

```rust
match tl {
    WindowSurface::Wayland((s, _)) => {
        // do something with surface
    }
    #[cfg(feature = "xwayland")]
    WindowSurface::X11(s) => {
        if let Some(surface) = &s.wl_surface() {
            // do something with surface. if it hasn't been matched with the X11Window yet, we might skip some important state updates.
        }
    }
}
```

But this is just a drive-by suggestion from someone who's still learning this stack, feel free to ignore me.

**Comment by Drakulix** [comment]
> because of a race. 

It's also not because of a race. X11 clients can unmap an X11 window again, which will cause Xwayland to remove the wl_surface again. And it can also be mapped again, which will cause it to get another wl_surface!

This is part of the reason why I feel like `Window` abstracts very poorly over X11Window.

> Fixes are applied to Smallvil and Anvil to make them compile and work. But to take full advantage of this PR, Anvil may need major refactor in the future.

Yeah for anvil this large refactor would need to be part of this PR. If anvil isn't even remotely doing what is best practice using smithay, we might as well delete it.

Also at least the geometry code is painfully wrong, the two function have the same name, but the result haves widely different meanings and X11surface's geometry also needs to be updated to work correctly.

Additionally I see no way to access the X11Surface type from a window.

**Comment by saihaze** [comment]
OK. Seems that this PR is a bad design. I will try something new.

**Comment by Drakulix** [comment]
> OK. Seems that this PR is a bad design. I will try something new.

I don't think the PR is in general a bad idea. I just feel like the `Window` type needs many more changes for this to be usable.

**Comment by saihaze** [comment]
> I don't think the PR is in general a bad idea. I just feel like the Window type needs many more changes for this to be usable.
Maybe I can introduce a new type for this? Name it like `GenericWindow`. It will be an Anvil `WindowElement` without server-side decorations. Then I will rewrite some parts of Anvil to take advantage of it.

**Comment by Drakulix** [comment]
> > I don't think the PR is in general a bad idea. I just feel like the Window type needs many more changes for this to be usable.
> 
> Maybe I can introduce a new type for this? Name it like `GenericWindow`. It will be an Anvil `WindowElement` without server-side decorations. Then I will rewrite some parts of Anvil to take advantage of it.

Feel free to start with that, if that feels easier. Though I would like to eventually unify this into a single `Window` type.

**Pull request closed without merging**
