### PR TITLE
Bump "nix" to 0.25.0

### PR DESCRIPTION
**Pull request by electron271**
Getting errors with old version of nix

### CODE REVIEW

**Comment by PolyMeilex** [comment]
Hi, Thanks for the PR.
I think that [drm-rs](https://github.com/Smithay/drm-rs) has to be updated first, otherwise we will end up with two versions of nix crate, and types will mismatch in some places.

**Comment by electron271** [comment]
https://github.com/Smithay/drm-rs/pull/129

> Hi, Thanks for the PR. I think that [drm-rs](https://github.com/Smithay/drm-rs) has to be updated first, otherwise we will end up with two versions of nix crate, and types will mismatch in some places.
> 
> EDIT: yep, looks like it already broke in CI

**Comment by electron271** [comment]
Here are the other packages that are on the old version of nix:
calloop
drm (pr sent)
drm-ffi
smithay-client-toolkit
wayland-backend
wayland-client
wayland-commons
wayland-cursor
wayland-server
wlcs_anvil
x11rb
x11rb-protocol

these are a lot of packages, this may not possible
i did a (very bad) attempt of replacing the versions, it could be a actual error in the code looking further

**Comment by PolyMeilex** [comment]
> Here are the other packages that are on the old version of nix:
> calloop
> drm (pr sent)
> drm-ffi
> smithay-client-toolkit
> wayland-backend
> wayland-client
> wayland-commons
> wayland-cursor
> wayland-server
> wlcs_anvil
> x11rb
> x11rb-protocol

Thanks for the list, we control everything on that list except x11rb so the update should be relatively straight forward.

**Comment by bwidawsk** [comment]
I think this can be closed

**Comment by PolyMeilex** [comment]
Indeed we are on 0.26 now

**Pull request closed without merging**
