### PR TITLE
added scroll events to pointer and winit demo

### PR DESCRIPTION
**Pull request by wmww**
My first PR here (and in Rust anywhere). I'm not sure the correct way to pass around the axis enum (input::Axis, wl_pointer::Axis, or something else). I went with wl_pointer::Axis. I tested with weston-eventdemo and weston-terminal and everything seems to work. Merge, edit or ignore as you wish.

### CODE REVIEW

**Comment by wmww** [comment]
Idk what those errors are. Like I said, I'm new to Rust. You can see from the diff that I didn't screw anything up too badly.

**Comment by jplatte** [comment]
@wmww Don't worry, I had a look and none of these are your fault. 205.5 is just static.rust-lang.org having issues when the Travis job was running, 205.22 is rustfmt-nightly not having been updated to work with the latest nightly and 205.23 is clippy, which I'm surprised is part of the CI at all, considering #45.

**Comment by vberger** [comment]
Thanks for the pull request @wmww ! Your code is good, and as @jplatte noted the travis failures are spurious.

I don't have much to say regarding your PR, given we currently advertise wl_seat version 4, your implementation is good, and I feel handling higher versions of wl_seat requires it's own issue (that I'll create right now).

**Comment by vberger** [comment]
Follow-up for more detailed axis events is in #54 if you are interested to continue on this track. :)

**Pull request merged**
