### PR TITLE
Security Context protocol

### PR DESCRIPTION
**Pull request by ids1024**
The compositor should not expose the `wp_security_context_manager_v1` global to clients connected to a security context. Otherwise, I guess this would be up to the compositor to set its own restrictions.

This implementation is currently incomplete.

### CODE REVIEW

**Comment by ids1024** [comment]
Rebased on top of https://github.com/Smithay/smithay/pull/1108, so CI can pass. This seems to be working correctly now, testing Anvil with a flatpak containing the wayland-rs `list_globals` example, I can confirm the security context global appear when run in a flatpak when `flatpak` is built from master with support for this.

**Review by Drakulix — APPROVED** [review]
Looks good to me in general, though I wonder, if we should force `can_view` to just return false for any client, that already has a security context?

While I am all for flexibility, I am not sure, for what scenario you could want a faulty implementation.

A filter for more restrictive filtering could still be provided.

**Comment by ids1024** [comment]
>  I wonder, if we should force can_view to just return false for any client, that already has a security context?

I think so, but I couldn't think of a good way to do that. The `ClientData` associated with the client is managed by the compositor, not Smithay, so I don't know if Smithay has a good way to test if `Client` has a security context... except by having a method to query that implemented by the compositor.

If Smithay doesn't use the security context for anything except excluding clients with a security context from using this protocol, the filter function already handles that so it's a bit redundant to add anything else.

**Comment by Drakulix** [comment]
> > I wonder, if we should force can_view to just return false for any client, that already has a security context?
> 
> I think so, but I couldn't think of a good way to do that. The `ClientData` associated with the client is managed by the compositor, not Smithay, so I don't know if Smithay has a good way to test if `Client` has a security context... except by having a method to query that implemented by the compositor.

We could add a trait requirement on `ClientData` to the implementation, so that we could query the security context. Though I get how that might be a bit annoying.

> If Smithay doesn't use the security context for anything except excluding clients with a security context from using this protocol, the filter function already handles that so it's a bit redundant to add anything else.

Smithay itself wouldn't do anything else, but I think it is a good idea to allow downstream to add additional filters.

**Comment by ids1024** [comment]
I don't think there's anywhere we could a dd a trait bound for the `ClientData` since that uses dynamic dispatch, and `insert_client` is called by the compositor. And yeah, that would be a bit annoying and add some complexity if it were possible.

**Comment by Drakulix** [comment]
Yeah, I remember [creative workarounds](https://smithay.github.io/smithay/smithay/wayland/compositor/trait.CompositorHandler.html#tymethod.client_compositor_state) to this I wrote in the past. They wouldn't really add any more safety over this approach.

**Comment by ids1024** [comment]
Yeah, I thought about something like that. Though you couldn't even call `client_compositor_state` in a `can_view` function since it is only passed the `client` and `global_data`, not the compositor's state.

And if it's only going to be used to test `is_some`, that's basically just a slightly more complicated filter function.

**Comment by Drakulix** [comment]
Right. I am gonna merge this as is, once the CI-PR has been sorted out.

**Pull request merged**
