### PR TITLE
fix: typo in README

### PR DESCRIPTION
**Pull request by tristonarmstrong**
Super complex; Please review thoroughly!

### CODE REVIEW

**Review by PolyMeilex — APPROVED** [review]
Sorry fo the delay, it took quite some time to review all of this.

**Comment by PolyMeilex** [comment]
Gush, new clippy lints, I will deal with that first, and then we can merge this, I'm hoping to not cause any conflicts.

**Comment by tristonarmstrong** [comment]
If there are any conflicts I'm sure i can handle it. I hope anyway 😆

**Comment by PolyMeilex** [comment]
Sure, just rebase (so CI passes) and this should be good to go.

**Comment by tristonarmstrong** [comment]
consider it done!

**Comment by PolyMeilex** [comment]
Thanks for taking the time!

**Pull request merged**
