### PR TITLE
Address some more clippy warnings

### PR DESCRIPTION
**Pull request by yzhs**
More work towards #45. Should I run cargo fmt on the changed files, all files, or not at all?

### CODE REVIEW

**Comment by vberger** [comment]
Looks good to me, thanks! Please don't run rustfmt for now. We'll do a rustfmt PR when it'll not risk to interfere with ongoing work.

@Drakulix how much does this interferes with your ongoing work, are you ok with me merging it?

**Comment by yzhs** [comment]
Ok, cool.

**Comment by Drakulix** [comment]
@vberger Should be very easy to rebase on top of these changes. I have no objections.

**Comment by vberger** [comment]
Alright! Thanks!

**Pull request merged**
