### PR TITLE
keyboard: allow setting keymap directly

### PR DESCRIPTION
**Pull request by nicolasavru**
Also make the Layout.0 public to allow constructing Layouts from u32s.

### CODE REVIEW

**Comment by Drakulix** [comment]
To be clear: I don't oppose this change.
But what is the use-case for it? It would be easier to review and judge if this should be part of the public api, if I would knew what exactly you do with it.

**Comment by nicolasavru** [comment]
A passthrough compositor. In the wayland client part of my code, I'm getting the keymap as a string/file descriptor and the layout index from update_modifiers (https://github.com/Smithay/client-toolkit/pull/430 for that), and need to pass that information on to clients running against my compositor. So I have the full keymap file and can construct a Keymap, but I don't have the RMLVO string which is what compositors usually construct a keymap from.

**Review by kchibisov — APPROVED** [review]

**Review by Drakulix — APPROVED** [review]

**Comment by ids1024** [comment]
https://github.com/Smithay/smithay/pull/750 has something similar. But I noticed the API is potentially unsound since `xkb::Keymap` is reference-counted, in a way that isn't thread safe. (See the unsafe `Send` impl in `src/input/keyboard/mod.rs`).

**Comment by nicolasavru** [comment]
I can modify this api to accept a String instead and construct the keymap inside set_keymap with Keymap::new_from_string (that's how I'm constructing the Keymap outside the function currently). I'll send a pr for that in a few min.

**Comment by nicolasavru** [comment]
#1221 for that change. Thanks for catching that.

**Pull request merged**
