### PR TITLE
Bump `udev` to 0.7 and `input` to 0.8.1

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by ids1024** [comment]
The failing CI check could be fixed by specifying the version of `udev` in `ci.yaml`, but perhaps it would be better to just release https://github.com/Smithay/input.rs and update to it, so only the latest version of the `udev` crate is used.

**Comment by ids1024** [comment]
Input 0.8 fails to build with `cargo build --no-default-features --features libinput_1_14`, which is what Smithay is currently using.

**Comment by Drakulix** [comment]
Input 0.8.1 is released. (*sigh*)

**Review by Drakulix — APPROVED** [review]
More safe-io goodness

**Pull request merged**
