### PR TITLE
Update `gbm` to 0.18

### PR DESCRIPTION
**Pull request by ids1024**
Depends on https://github.com/Smithay/gbm.rs/pull/25.

### CODE REVIEW

**Comment by Drakulix** [comment]
> I updated this, but I noticed there's still an unused generic: [Smithay/gbm.rs#48](https://github.com/Smithay/gbm.rs/pull/48).
> 
> It could be merged as is now, though it has to pass something explicitly as that generic. Annoying that clippy doesn't say anything about unused generics.

v0.18 is inbound here https://github.com/Smithay/gbm.rs/actions/runs/12126008784

**Comment by ids1024** [comment]
> It seems package 'gbm-sys' modified since '0.3.1' so new version should be published

**Comment by Drakulix** [comment]
> > It seems package 'gbm-sys' modified since '0.3.1' so new version should be published

https://github.com/Smithay/gbm.rs/actions/runs/12143920979/job/33862081369

**Review by Drakulix — APPROVED** [review]
Looks good!

**Pull request merged**
