### PR TITLE
anvil: xkbcommon library update

### PR DESCRIPTION
**Pull request by akane6704**

### CODE REVIEW

**Review by PolyMeilex — APPROVED** [review]
I don't see any obvious regressions, so LGTM.

**Review by PolyMeilex — CHANGES_REQUESTED** [review]
Actually smithay dep should be updated as well: here https://github.com/Smithay/smithay/blob/003726dd7430629824822850349fbaddc32e1808/Cargo.toml#L62

**Comment by akane6704** [comment]
> Actually smithay dep should be updated as well: here
> 
> https://github.com/Smithay/smithay/blob/003726dd7430629824822850349fbaddc32e1808/Cargo.toml#L62

Done!

**Comment by akane6704** [comment]
np!

**Pull request merged**
