### PR TITLE
Feature/egl context priority

### PR DESCRIPTION
**Pull request by cmeissl**
This PR adds support for egl context priority using the [EGL_IMG_context_priority](https://registry.khronos.org/EGL/extensions/IMG/EGL_IMG_context_priority.txt) egl extension.

It also changes the multigpu code to request a high priority context by default.

### CODE REVIEW

**Comment by Drakulix** [comment]
Can we make the second commit add the priority as constructor arguments for the `GbmGlesBackend` and `EglGlesBackend` instead?

**Comment by cmeissl** [comment]
> Can we make the second commit add the priority as constructor arguments for the `GbmGlesBackend` and `EglGlesBackend` instead?

Yes, though we only have a default impl and `with_factory`. I can add a new function taking the priority, but what should the default do? An alternative would be to not request any priority by default and use the factory for this. I considered that first, but that forces downstream to use the factory which can be easily forgotten.

**Comment by Drakulix** [comment]
> > Can we make the second commit add the priority as constructor arguments for the `GbmGlesBackend` and `EglGlesBackend` instead?
> 
> Yes, though we only have a default impl and `with_factory`. I can add a new function taking the priority, but what should the default do? An alternative would be to not request any priority by default and use the factory for this. I considered that first, but that forces downstream to use the factory which can be easily forgotten.

I guess we have two options:
- Make `Default` do what it currently does. A context with "medium" or "default" priority. Additionally add a `with_priority`-constructor. The factory-constructor would remain unchanged.
- Drop `Default` imo and force downstream to always specify a priority or at least explicitly pass `None` for "default priority" (if not using a factory).

I am happy with both options.

**Comment by i509VCB** [comment]
I believe vulkan has an extension similar to this, so we can elect to specify a priority from the multigpu code, although it's an optional extension: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_global_priority.html

**Comment by cmeissl** [comment]
> > > Can we make the second commit add the priority as constructor arguments for the `GbmGlesBackend` and `EglGlesBackend` instead?
> > 
> > 
> > Yes, though we only have a default impl and `with_factory`. I can add a new function taking the priority, but what should the default do? An alternative would be to not request any priority by default and use the factory for this. I considered that first, but that forces downstream to use the factory which can be easily forgotten.
> 
> I guess we have two options:
> 
>     * Make `Default` do what it currently does. A context with "medium" or "default" priority. Additionally add a `with_priority`-constructor. The factory-constructor would remain unchanged.
> 
>     * Drop `Default` and force downstream to always specify a priority or at least explicitly pass `None` for "default priority" (if not using a factory).
> 
> 
> I am happy with both options.

I opted for the first option, which really seems more sensible as `Medium` is defined as the default by the spec (and it does not break the API)

**Review by Drakulix — APPROVED** [review]

**Pull request merged**
