### PR TITLE
0.30: update to alpha6

### PR DESCRIPTION
**Pull request by i509VCB**
WlEglSurface is no longer Sync, so EGLNativeDisplay is only implemented for `Mutex<WlEglSurface>`.

### CODE REVIEW

**Review by PolyMeilex — APPROVED** [review]
LGTM

**Comment by Drakulix** [comment]
Actually this is not the correct fix.

You cannot bind the same EGLSurface across multiple threads, so EGLNativeSurface should just not require `Sync`, only `Send`.

Same goes for EGLContext, which cannot be bound from multiple threads and is thus also not Sync.

Only the EGLDisplay and EGLImage/Buffer/BufferReader are truely Sync.

So we should not need the mutex.

**Comment by i509VCB** [comment]
Hmm okay, so this needs some larger changes to be correct.

**Comment by i509VCB** [comment]
Also added suppression on the delegate macro docs for now since we need to know if the code compiles or not.

**Review by Drakulix — APPROVED** [review]
EGL side now also looks good to me

**Pull request merged**
