### PR TITLE
ci: Enforce 1.59 MSRV

### PR DESCRIPTION
**Pull request by Drakulix**

### CODE REVIEW

**Review by PolyMeilex — APPROVED** [review]
1.59 sounds good to me. No objections, once GATs are a thing I would strongly consider bumping it, but now 1.59 is definitely enough.

**Comment by Drakulix** [comment]
> once GATs are a thing I would strongly consider bumping it

Agreed. This PR is not about forcing 1.59 indefinitely, but rather enforcing **a** version at all and getting rid of CI failing every time a new rust version comes out and new clippy lints come in.

**Comment by cmeissl** [comment]
As long as we can agree that bumping the MSRV needs some planning/coordination I am totally fine with this decission :)
Once GATs are a thing I will make sure we can meet the required MSRV.

**Comment by PolyMeilex** [comment]
> As long as we can agree that bumping the MSRV needs some planning/coordination I am totally fine with this decission :) Once GATs are a thing I will make sure we can meet the required MSRV.

Yeah, I think that in the future, a PR that bumps the MSRV will be a good place where everyone will be able to voice theirs opinions and concerns, before it gets merged. It will give the whole process more structure.

**Review by vberger — APPROVED** [review]

**Review by i509VCB — APPROVED** [review]
1.59 is fine, I already use the latest rustc anyways.

**Pull request merged**
