### PR TITLE
Prepare desktop::Window for XWayland

### PR DESCRIPTION
**Pull request by saihaze**
As mentioned in the document, `desktop::Window` will eventually have XWayland support. The related issue is https://github.com/Smithay/smithay/issues/1202.

### CODE REVIEW

**Review by Drakulix — APPROVED** [review]
Thanks! This looks exactly as I hoped.

Perhabs these changes might even make Xwayland support in smallvil something work considering. (Ping @PolyMeilex)

**Comment by cmeissl** [comment]
This seems to have at least broken `epiphany`, since this commit its output stays black and the command line is spammed with warnings and errors.

**Comment by saihaze** [comment]
> This seems to have at least broken `epiphany`, since this commit its output stays black and the command line is spammed with warnings and errors.

You mean GNOME Web? Web 45.2 still works on Anvil.

**Comment by cmeissl** [comment]
> > This seems to have at least broken `epiphany`, since this commit its output stays black and the command line is spammed with warnings and errors.
> 
> You mean GNOME Web? Web 45.2 still works on Anvil.

Yes, Gnome Web. You sure you tried with XWayland? Because that is what changed and is now broken. Easiest way is to launch with WAYLAND_DISPLAY unset.

**Comment by saihaze** [comment]
> Yes, Gnome Web. You sure you tried with XWayland? Because that is what changed and is now broken. Easiest way is to launch with WAYLAND_DISPLAY unset.

Oh, I tried with Wayland. My patch was only tested with GIMP for XWayland support, and it worked. I will try Epiphany XWayland later.

**Comment by ids1024** [comment]
Interestingly, Epiphany doesn't seem to error on my Pop!_OS 22.04 system (but that's a GTK3 version). Nor do I see similar issues with other things I test there (including gtk4-demo). But I can reproduce this at least with Epiphany on Debian Sid:

```
(epiphany:64721): Gtk-WARNING **: 15:02:24.666: gtk_widget_size_allocate(): attempt to allocate AdwDialogHost dialog-host 0x5d88fad9edf0 with width -9 and height -9

(epiphany:64721): Gtk-CRITICAL **: 15:02:24.668: gtk_widget_set_size_request: assertion 'width >= -1' failed

(epiphany:64721): Gtk-WARNING **: 15:02:24.688: gtk_widget_size_allocate(): attempt to allocate AdwDialogHost dialog-host 0x5d88fad9edf0 with width -9 and height -9

(epiphany:64721): Adwaita-WARNING **: 15:02:24.688: AdwTabOverview 0x5d88fad88930 exceeds EphyWindow size: requested 310×126 px, 0×0 px available
```

So something is wrong with how the compositor is sizing XWayland windows.

**Comment by cmeissl** [comment]
> Interestingly, Epiphany doesn't seem to error on my Pop!_OS 22.04 system (but that's a GTK3 version). Nor do I see similar issues with other things I test there (including gtk4-demo). But I can reproduce this at least with Epiphany on Debian Sid:
> 
> ```
> (epiphany:64721): Gtk-WARNING **: 15:02:24.666: gtk_widget_size_allocate(): attempt to allocate AdwDialogHost dialog-host 0x5d88fad9edf0 with width -9 and height -9
> 
> (epiphany:64721): Gtk-CRITICAL **: 15:02:24.668: gtk_widget_set_size_request: assertion 'width >= -1' failed
> 
> (epiphany:64721): Gtk-WARNING **: 15:02:24.688: gtk_widget_size_allocate(): attempt to allocate AdwDialogHost dialog-host 0x5d88fad9edf0 with width -9 and height -9
> 
> (epiphany:64721): Adwaita-WARNING **: 15:02:24.688: AdwTabOverview 0x5d88fad88930 exceeds EphyWindow size: requested 310×126 px, 0×0 px available
> ```
> 
> So something is wrong with how the compositor is sizing XWayland windows.

But something seems to have changed in this PR, using an earlier commit makes Epiphany work again (at least for me) on x11.

**Comment by ids1024** [comment]
Yeah, it works before this commit. This must be doing something wrong with how the size of XWayland windows is configured. But in a way that only breaks certain clients.

**Pull request merged**
