### PR TITLE
Cargo.toml: include repo, update nix/image

### PR DESCRIPTION
**Pull request by serprex**

### CODE REVIEW

**Comment by serprex** [comment]
(the ci spam is because I don't have enough RAM to compile Smithay)

**Comment by Timidger** [comment]
@serprex fyi, `cargo check ` should be usable even if you can't compile the entire program

**Comment by Drakulix** [comment]
@serprex Welcome and thanks for you contribution!

Sadly rustfmt seems not to agree with you. Could you possibly sort out these errors: https://travis-ci.org/Smithay/smithay/jobs/285128442

We are using rustfmt-nightly. You can get it using `cargo install rustfmt-nightly`.

**Comment by serprex** [comment]
I fixed the rustfmt nits in unrelated code. Unfortuantely there are now some expired ppa keys in Ubuntuland

**Comment by vberger** [comment]
Ah, looks like we have some travis issues. I'll look into at that.

**Comment by vberger** [comment]
#52 should have fixed it. Could you rebase?

**Comment by serprex** [comment]
Done

**Comment by vberger** [comment]
All is good, thanks!

**Pull request merged**
