### PR TITLE
Solve issue #161

### PR DESCRIPTION
**Pull request by mcmfb**
Implement a Serial type whose comparison takes the underlying counter's wrap-around into account, and use this type instead of u32 for all serials.

### CODE REVIEW

**Comment by mcmfb** [comment]
> I think It would be worth adding `From` impls for converting between `Serial` and `u32` (so `impl From<u32> for Serial` and `impl From<Serial> for u32`), and then use `.into()` for conversions between the two, rather than making the inner field public. Seems cleaner to me that way.

Indeed it does. Will do!

> Also, it looks like the CI is unhappy about formatting, please run `cargo fmt` on your commits to make it happy. :)

Oops, my bad. I'll fix that too.

**Comment by vberger** [comment]
Thanks, this looks quite good!

The clippy failure is unrelated to your PR, so no need to worry about it.

Thinking a little more about it, if you could add a few unit tests for the `PartialOrd` impl, just to future-proof the whole thing in case we come back to modify it at some point, that'd be perfect.

**Comment by mcmfb** [comment]
> The clippy failure is unrelated to your PR, so no need to worry about it.

Oh, ok, I was wondering about that too.
 
> Thinking a little more about it, if you could add a few unit tests for the `PartialOrd` impl, just to future-proof the whole thing in case we come back to modify it at some point, that'd be perfect.

Done. If there's any other test cases I should include, just let me know.
Since tests in Rust are run in parallel, I've assumed I can't use the global SERIAL_COUNTER, so I've made a new SerialCounter for each test.

**Comment by vberger** [comment]
Sorry for the late reply, this is good from my point of view, thanks!

**Pull request merged**
