### PR TITLE
Perf/profiling

### PR DESCRIPTION
**Pull request by cmeissl**
Some changes I have been using locally for profiling anvil/smithay, mainly with `tracy`.

Example:

Screenshot from 2023-06-29 11-53-02

### CODE REVIEW

**Review by Drakulix — COMMENTED** [review]
Awesome. I meant to do this at some point, highly appreciated.

**Comment by cmeissl** [comment]
> Awesome. I meant to do this at some point, highly appreciated.

Cool, I was not sure there is interest in it as we already have `tracing` and this adds another dependency. Though if no feature is enabled the dependency should be a no-op.

**Review by PolyMeilex — APPROVED** [review]
This sounds awesome!
Just off curiosity, how does this differ from something like `tracing_tracy`?

**Comment by cmeissl** [comment]
> This sounds awesome! Just off curiosity, how does this differ from something like `tracing_tracy`?

With this the use of `tracing_tracy` is still possible. Initially I used `tracing_tracy`, but the result were a bit off. For getting meaningful data you would have to enable the trace log level which is pretty heavy in smithay as we log some quite big messages. So using `profiling` with `tracy_client` is way more lightweight and it also leaves the decision to downstream which framework it wants to use.

**Review by Drakulix — APPROVED** [review]

**Pull request merged**
