### PR TITLE
Track entered surfaces in Output

### LINKED ISSUE #1138: Surfaces don't get WlOutput.enter() if they bind the global late
If I call `window.output_enter(output)` and the surface binds the global only afterwards, then it will never get the enter event on that global. This can happen for example when a compositor places existing windows on a newly connected monitor, calling `output_enter()` on them, before the windows had a chance to bind the global.

### PR DESCRIPTION
**Pull request by YaLTeR**
Fixes #1138

### CODE REVIEW

**Comment by cmeissl** [comment]
tbh I am not happy with creating a dependency from the generic wayland abstractions to the desktop module.
this can be quite surprising, hard to find and won't help if you do not use the desktop module.

**Comment by YaLTeR** [comment]
How should this be done instead? Maybe `Output` itself should keep a list of surfaces that are currently "entered" on it, and send the events to those? That should make it work for everyone I think?

**Comment by Drakulix** [comment]
> There already are output.enter()/leave() but they have the same problem that if you use them, you don't know when a new output is bound. Ideally Output itself should keep track of it.

Right, which is why those methods shouldn't just send the event, but internally track surfaces.

**Comment by YaLTeR** [comment]
So I just replace OutputSurfacesUserdata with the same tracking on the output itself?

**Comment by YaLTeR** [comment]
Did that, how does that look? There's no `Output::cleanup()` but desktop did it on enter/leave, so I just preserved that.

**Review by Drakulix — COMMENTED** [review]
Looks like a proper fix to me. @cmeissl any additional thoughts?

**Comment by cmeissl** [comment]
Nope, really happy how that turned out, thanks!

**Review by Drakulix — APPROVED** [review]

**Pull request merged**
